CREATE TYPE  T_PROCEDENCIAS AS OBJECT (
COD  VARCHAR2  (2),
CIUDAD  VARCHAR2(20),
PAIS VARCHAR2 (20)
)
/

CREATE OR  REPLACE TYPE  T_ARTICULOS  AS OBJECT (
  ID    VARCHAR2 (5),
  DESCRIPCION     VARCHAR2(50),
  STOCKACTUAL  NUMBER(4),
  STOCKMINIMO  NUMBER(2),
  PVP  NUMBER(4),
  ORIGEN  REF T_PROCEDENCIAS
)
/

CREATE TABLE ARTICULOS2 OF T_ARTICULOS (
CONSTRAINT  PK_ART PRIMARY KEY (ID)
);
CREATE TABLE  PROCEDENCIAS2 OF T_PROCEDENCIAS (
CONSTRAINT PK_PROC PRIMARY KEY (COD)
);

INSERT   INTO   PROCEDENCIAS2 VALUES (T_PROCEDENCIAS('1', 'TOLEDO', 'ESPAÑA'));
INSERT   INTO   PROCEDENCIAS2 VALUES (T_PROCEDENCIAS('2', 'MILAN', 'ITALIA'));
INSERT   INTO   PROCEDENCIAS2 VALUES (T_PROCEDENCIAS('3', 'OPORTO', 'PORTUGAL'));
INSERT   INTO   PROCEDENCIAS2 VALUES (T_PROCEDENCIAS('4', 'MADRID','ESPAÑA'));